name: Build, test and lint
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn test
      - run: yarn lint
      - run: yarn dist
